server:
  port: 9002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
      url: jdbc:mysql://localhost:3306/onlineshop?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: fhl
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5

mybatis:
  mapper-locations: classpath*:stu/swufe/fhl/demo/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml


